CarDealership/CarDealership/CarDealership.UI/Controllers/RequestFormController.cs
using CarDealership.Data;
using CarDealership.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarDealership.Controllers
{
    public class RequestFormController : Controller
    {
        // GET: RequestForm
        public ActionResult List()
        {
            var repo = new RequestRepository();
            var allForms = repo.GetAll();
            return View(allForms);
        }

        public ActionResult Details(int id)
        {
            var repo = new RequestRepository();
            var form = repo.GetById(id);
            return View(form);
        }

        public ActionResult NewForm(int id)
        {
            var newForm = new RequestForm();
            newForm.VehicleId = id;
            return View(newForm);
        }

        [HttpPost]
        public ActionResult NewForm(RequestForm newForm)
        {
            var repo = new RequestRepository();
            newForm.RequestFormStatus = RequestFormStatus.New;
            newForm.LastContacted = null;
            repo.Add(newForm);

            return RedirectToAction("ListCars", "Home");
        }

        public ActionResult DeleteForm(int id)
        {
            var repo = new RequestRepository();
            var form = repo.GetById(id);
            return View(form);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteForm(RequestForm form)
        {
            var repo = new RequestRepository();
            repo.Delete(form.RequestFormId);

            return RedirectToAction("List");
        }

        public ActionResult UpdateForm(int id)
        {
            var repo = new RequestRepository();
            var form = repo.GetById(id);
            return View(form);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult UpdateForm(RequestForm form)
        {
            var repo = new RequestRepository();
            repo.Update(form.RequestFormId, form);
            return RedirectToAction("List");
        }
    }
}

CarDealership/CarDealership/CarDealership.UI/Views/RequestForm/DeleteForm.cshtml
@model CarDealership.Models.RequestForm

@{
    ViewBag.Title = "DeleteForm";
}

<h2>Delete Request Form</h2>

<table class="table-striped">
    <thead>
        <tr>
            <th><b>Vehicle ID</b></th>
            <th><b>First Name</b></th>
            <th><b>Last Name</b></th>
            <th><b>Phone Number</b></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Model.VehicleId</td>
            <td>@Model.FirstName</td>
            <td>@Model.LastName</td>
            <td>@Model.PhoneNumber</td>
            <td>
                <form action="@Url.Action("DeleteForm")" method="POST">
                    <input type="hidden" name="RequestFormId" id="RequestFormId" value="@Model.RequestFormId" />
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </form>
            </td>
            <td>@Html.ActionLink("Go back to List", "List", null, new { @class = "btn btn-success" })</td>
        </tr>
    </tbody>
</table>

CarDealership/CarDealership/CarDealership.UI/Views/RequestForm/Details.cshtml
@model CarDealership.Models.RequestForm

@{
    ViewBag.Title = "Details";
}

<h2>Details of Request Form</h2>

<p><b>Vehicle ID:</b> @Model.VehicleId</p>
<p><b>Status of Request:</b> @Model.RequestFormStatus</p>
<p><b>Date Last Contacted:</b> @Model.LastContacted</p>
<p><b>First Name:</b> @Model.FirstName</p>
<p><b>Last Name:</b> @Model.LastName</p>
@if (Model.EmailAddress != string.Empty)
{
    <p><b>Email Address:</b> @Model.EmailAddress</p>
}
@if (Model.PhoneNumber != string.Empty)
{
    <p><b>Phone Number:</b> @Model.PhoneNumber</p>
}
@if (Model.BestTimeToCall != string.Empty)
{
    <p><b>Best Time to Call:</b> @Model.BestTimeToCall</p>
}

<p><b>Preferred Contact Method:</b> @Model.PreferedContactMethod</p>

@if (Model.DateNeedToPurchaseBy != null)
{
    <p><b>Need to purchase by:</b> @Model.DateNeedToPurchaseBy.Value.ToString("MM-dd-yyyy")</p>
}
@if (Model.LastContacted != null)
{
    <p><b>Last Contact Date:</b> @Model.LastContacted.Value.ToString("MM-dd-yyyy")</p>
}
@if (Model.AdditionalInfo != string.Empty)
{
    <p><b>Additional Information:</b> @Model.AdditionalInfo</p>
}

<td>@Html.ActionLink("Go back to List", "List", null, new { @class = "btn btn-success" })</td>

CarDealership/CarDealership/CarDealership.UI/Views/RequestForm/List.cshtml
@using System.Web.Mvc.Html
@model List<CarDealership.Models.RequestForm>

@{
    ViewBag.Title = "List";
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>List</title>
</head>
<body>
    <div>
        <h2>List of Request Forms</h2>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Status</th>
                    <th>Vehicle ID</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Phone</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var form in Model)
                {
                    <tr>
                        <td>@form.RequestFormStatus</td>
                        <td>@form.VehicleId</td>
                        <td>@form.FirstName</td>
                        <td>@form.LastName</td>
                        <td>@form.PhoneNumber</td>
                        <td>@Html.ActionLink("Details", "Details", new { id = form.RequestFormId }, new { @class = "btn btn-success" })</td>
                        <td>@Html.ActionLink("Edit", "UpdateForm", new { id = form.RequestFormId }, new { @class = "btn btn-default" })</td>
                        <td>@Html.ActionLink("Delete", "DeleteForm", new { id = form.RequestFormId }, new { @class = "btn btn-danger" })</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <br />
</body>
</html>

CarDealership/CarDealership/CarDealership.UI/Views/RequestForm/NewForm.cshtml
@model CarDealership.Models.RequestForm

@{
    ViewBag.Title = "NewForm";
}

@using (Html.BeginForm("NewForm", "RequestForm", FormMethod.Post, new { @class = "form-horizontal", id = "AddRequest" }))
{
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label>Vehicle ID - @Model.VehicleId</label>
                @Html.HiddenFor(m => m.VehicleId)
            </div>
            <div class="form-group">
                <label>First Name</label>
                @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Last Name</label>
                @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Phone Number</label>
                @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Best Time to Call</label>
                @Html.TextBoxFor(m => m.BestTimeToCall, new { @class = "form-control" })
            </div>
        </div>
        <div class="col-md-6">
            <p></p>
            <p></p>
            <br />
            <br />
            <div class="form-group">
                <label>Preferred Contact Method</label>
                @Html.EnumDropDownListFor(m => m.PreferedContactMethod, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Date to Purchase by</label>
                @Html.EditorFor(m => m.DateNeedToPurchaseBy, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Additional Information</label>
                @Html.TextBoxFor(m => m.AdditionalInfo, new { @class = "form-control" })
            </div>
            <br />
            <br />
            <br />

            <div>
                <a href="javascript:history.back()" class="btn btn-danger">Cancel</a>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </div>
}
@section scripts
{
    <script src="~/Scripts/app/AddRequestValidate.js"></script>
    <script src="~/Scripts/app/DefaultValidation.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
}

CarDealership/CarDealership/CarDealership.UI/Views/RequestForm/UpdateForm.cshtml
@model CarDealership.Models.RequestForm

@{
    ViewBag.Title = "EditForm";
}

<h2>Edit Request Form</h2>

@using (Html.BeginForm("UpdateForm", "RequestForm", FormMethod.Post))
{
    @Html.HiddenFor(m => m.RequestFormId, new { @class = "form-control" })
    <div>
        <label>Request Form Status:</label><br />
        @Html.EnumDropDownListFor(m => m.RequestFormStatus, new { @class = "form-control" })
    </div>
    <div>
        <label>Date Last Contacted:</label><br />
        @Html.EditorFor(m => m.LastContacted, new { @class = "form-control" })
    </div>

    <div>
        <label>First Name:</label><br />
        @Html.EditorFor(m => m.FirstName, new { @class = "form-control" })
    </div>
    <div>
        <label>Last Name:</label><br />
        @Html.EditorFor(m => m.LastName, new { @class = "form-control" })
    </div>
    <div>
        <label>Phone number:</label><br />
        @Html.EditorFor(m => m.PhoneNumber, new { @class = "form-control" })
    </div>

    <br />
    <div>
        <button class="btn btn-default" type="submit">Save</button>
        @Html.ActionLink("Go back to List", "List", null, new { @class = "btn btn-success" })
    </div>

}