CarDealership/SampleDealership/SampleDealership.UI/Controllers/RequestInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SampleDealership.Data;
using SampleDealership.Models;

namespace SampleDealership.UI.Controllers
{
    public class RequestInfoController : Controller
    {
        // GET: RequestInfo
        public ActionResult List()
        {
            var repo = new RequestInfoRepository();
            var allforms = repo.GetAllRequestForms();
            return View(allforms);
        }

        public ActionResult Details(int id)
        {
            var repo = new RequestInfoRepository();
            var form = repo.GetById(id);
            return View(form);
        }

        public ActionResult NewForm()
        {
            return View("NewForm",new RequestInformation());
        }

        [HttpPost]
        public ActionResult NewForm(RequestInformation newFrom)
        {
            var repo = new RequestInfoRepository();
            repo.Add(newFrom);

            return RedirectToAction("List");
        }

        public ActionResult DeleteForm(int id)
        {
            var repo = new RequestInfoRepository();
            var form = repo.GetById(id);
            return View(form);
        }
        
        [HttpPost]
        public ActionResult DeleteForm(RequestInformation form)
        {
            var repo = new RequestInfoRepository();
            repo.Delete(form.VehicleId);

            return RedirectToAction("List");
        }

        public ActionResult EditForm(int id)
        {
            var repo = new RequestInfoRepository();
            var form = repo.GetById(id);
            return View(form);
        }
        
        [HttpPost]
        public ActionResult EditForm(RequestInformation form)
        {
            var repo = new RequestInfoRepository();
            repo.Edit(form);

            return RedirectToAction("List");
        }
    }
}

CarDealership/SampleDealership/SampleDealership.UI/Views/RequestInfo/DeleteForm.cshtml
@model SampleDealership.Models.RequestInformation
@{
    ViewBag.Title = "DeleteForm";
}

<h2>Delete Request Form</h2>

<table>
    <thead>
    <tr>
        <th><b>Vehicle ID</b></th>        
        <th><b>Name</b></th>
        <th><b>Phone Number</b></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>@Model.VehicleId</td>
        <td>@Model.Name</td>
        <td>@Model.PhoneNumber</td>
        <td>
            <form action="@Url.Action("DeleteForm")" method="POST">
                <input type="hidden" name="VehicleId" id="VehicleId" value="@Model.VehicleId"/>
                <input type="submit" value="Delete" class="btn btn-danger"/>
            </form>
        </td>
        <td>@Html.ActionLink("Go back to List", "List", null, new { @class = "btn btn-success" })</td>
    </tr>
    </tbody>
</table>

CarDealership/SampleDealership/SampleDealership.UI/Views/RequestInfo/Details.cshtml
@model SampleDealership.Models.RequestInformation

@{
    ViewBag.Title = "Details";
}

<h2>Details of Request Form</h2>

<p><b>Vehicle ID:</b> @Model.VehicleId</p>
<p><b>Name:</b> @Model.Name</p>
<p><b>Email Address:</b> @Model.EmailAddress</p>
<p><b>Phone Number:</b> @Model.PhoneNumber</p>
<p><b>Best Time to Call:</b> @Model.BestTimeToCall</p>
<p><b>Preferred Contact Method:</b> @Model.PreferredContactMethod</p>
<p><b>Timefram to Purchase:</b> @Model.TimeframeToPurchase</p>
<p><b>Additional Information:</b> @Model.AdditionalInformation</p>
<p><b>Last Contact Date:</b> @Model.LastContactDate</p>
<p><b>Status of Request:</b> @Model.StatusOfRequest</p>


<td>@Html.ActionLink("Go back to List", "List", null, new { @class = "btn btn-success" })</td>

CarDealership/SampleDealership/SampleDealership.UI/Views/RequestInfo/EditForm.cshtml
@model SampleDealership.Models.RequestInformation

@{
    ViewBag.Title = "EditForm";
}

<h2>Edit Request Form</h2>


@using (Html.BeginForm("EditForm", "RequestInfo", FormMethod.Post))
{
    @Html.HiddenFor(m => m.VehicleId, new { @class = "form-control" })
        
    <div>
        <label>Name:</label><br/>
        @Html.EditorFor(m => m.Name, new { @class = "form-control" })
    </div>

    <div>
        <label>Phone number:</label><br/>
        @Html.EditorFor(m => m.PhoneNumber, new { @class = "form-control" })
    </div>
    <div>
        <label>Status of Request:</label><br />
        @Html.EditorFor(m => m.StatusOfRequest, new { @class = "form-control" })
    </div>

    <br/>
    <div>
        <input type="submit" value="Save" class="btn btn-success"/>
        @Html.ActionLink("Go back to List", "List", null, new { @class = "btn btn-success" })
    </div>

}

CarDealership/SampleDealership/SampleDealership.UI/Views/RequestInfo/List.cshtml
@model List<SampleDealership.Models.RequestInformation>

@{
    ViewBag.Title = "List";
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>List</title>
</head>
<body>
<div>
    <h2>List of Request Fomrs for Vehicles</h2>
    
        <table>
            <thead>
            <tr>
                <th>Vehicle ID</th>
                <th>Name</th>
                <th>Phone</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var form in Model)
            {
                <tr>
                    <td>@form.VehicleId</td>
                    <td>@form.Name</td>
                    <td>@form.PhoneNumber</td>
                    <td>@Html.ActionLink("Delete", "DeleteForm", new {id = form.VehicleId}, new {@class = "btn btn-danger"})</td>
                    <td>@Html.ActionLink("Edit", "EditForm", new {id = form.VehicleId}, new {@class = "btn btn-danger"})</td>
                    <td>@Html.ActionLink("Details", "Details", new {id = form.VehicleId}, new {@class = "btn btn-default"})</td>
                </tr>
            }
            </tbody>
        </table>
</div>

<br/>
<div>
    @Html.ActionLink("New Request", "NewForm", null, new {@class = "btn btn-success"})
</div>

</body>
</html>

CarDealership/SampleDealership/SampleDealership.UI/Views/RequestInfo/NewForm.cshtml
@model SampleDealership.Models.RequestInformation

@{
    ViewBag.Title = "NewForm";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>New Request</title>
</head>
<body>
    <div>
        <form action="/RequestInfo/NewForm" method="POST">
            <div class="form-group">
                <label>Vehicle ID</label>
                @Html.TextBoxFor(m => m.VehicleId, new {@class = "form-control"})
            </div>
            <div class="form-group">
                <label>Name</label>
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Phone Number</label>
                @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Best Time to Call</label>
                @Html.TextBoxFor(m => m.BestTimeToCall, new {@class = "form-control"})
            </div>
            <div class="form-group">
                <label>Preferred Contact Method</label>
                @Html.TextBoxFor(m => m.PreferredContactMethod, new {@class = "form-control"})
            </div>
            <div class="form-group">
                <label>Timeframe to Purchase</label>
                @Html.TextBoxFor(m => m.TimeframeToPurchase, new {@class = "form-control"})
            </div>
            <div class="form-group">
                <label>Additional Information</label>
                @Html.TextBoxFor(m => m.AdditionalInformation, new {@class = "form-control"})
            </div>
            <div class="form-group">
                <label>Last Contact Date</label>
                @Html.TextBoxFor(m => m.LastContactDate, new {@class = "form-control"})
            </div>
            <div class="form-group">
                <label>Status of Request</label>
                @Html.TextBoxFor(m => m.StatusOfRequest, new { @class = "form-control" })
            </div>

            <div>
                <input type="submit" value="Submit" class="btn btn-success"/>
                @Html.ActionLink("Go back to List", "List", null, new { @class = "btn btn-success" })
            </div>
    </form>
    </div>
</body>
</html>